version: "3.7"
services:
  dev-env:
    # set explicitly in case dir/project name is different
    image: eval-the-evil_dev-env
    build:
      context: .
      cache_from:
        # use image by the same name as cache, when reloaded on CircleCI
        - eval-the-evil_dev-env
    environment:
      - TERM # to get colors
      - GITHUB_TOKEN # for ghr/uploading release artifacts
    volumes:
      - ./bin:/root/eval-the-evil/bin:ro
      - ./src:/root/eval-the-evil/src:ro
    ports:
      - 3825:3825
    working_dir: /root/eval-the-evil
    command: |
      bash -c 'echo "Sleeping forever. Use exec or override command."; sleep infinity'
